<?php
	session_start();
	require 'dbconfig/config.php';
?>

<!DOCTYPE html>
<html>
 <head>
 
 
  <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> WebCOMS - Conference Management System </title>

    <!--<link rel="stylesheet" href="css/sty.css">
    <link rel="stylesheet" href="css/mychanged.css">
    <link rel="stylesheet" href="css/styleNavbar.css">-->


    <link rel="stylesheet" href="css/table_style.css">
	<link rel="stylesheet" href="css/about_help_styles.css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>


  </head>

<body>


  <!--Navigation bar-->
 <nav>
	<div class="logo">Web-COMS</div>
      <input type="checkbox" id="click">
            <label for="click" class="menu-btn">
              <i class="fas fa-bars"></i>
            </label>
		<ul>
			<li><a class="active" href="index.php">Home</a></li>
			<li><a href="login.php">Login</a></li>
			<li><a href="register.php">Register</a></li>
			<li><a href="help.php">Help</a></li>
			<li><a href="About.php">About</a></li>
		</ul>
		<br /><br />
	</nav>
  
  


  </br></br></br>
  <div>
  <p align=center >
  <i>
  Currently, different vendors provide conference management systems as a commercial
product. But there is no single platform to handle main processes in a conference. Also,
there is no auto-generated proceeding preparation in many of available systems. Most of
the CMSs support only to the paper submission process and paper review process and
they provide other major processes manually. Because of this reason conference
organizers must pay a huge effort and time to conduct other major processes. Therefore,
the availability of a single platform to handle main processes, availability of an autogenerated
 proceeding process are very important tasks in managing a conference
  
 
  </i>
  </p>
  </div>

  <?php
        include "forhomepage-conferenceList.php";
	?>


     <div class="footer">
            <p>&copy;2020, All rights reserved by www.WebComs.lk</p>
        </div>
</body>
</html>
